### ISSUE TITLE
Travis Issue

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/3-hmm#4]
@rivlev When i click on cisc 3410 from my profile page:
<img width="836" alt="screen shot 2017-11-22 at 12 37 53 pm" src="https://user-images.githubusercontent.com/25493211/33141725-044b5c78-cf82-11e7-8269-b2b9ac483673.png">
What should i do?

**Comment by myang310** [comment]
Paste in this page:
https://travis-ci.com/cisc3410/<repo-name>
(My repo name is 3-hmm-myang310 so it's https://travis-ci.com/cisc3410/3-hmm-myang310 for me).

You should be able to click a button to activate it there.

**Comment by myang310** [comment]
@MichaelGregg

**Comment by MichaelGregg** [comment]
thank you @myang310.  When i navigate to that page, this is what i see:
<img width="1135" alt="screen shot 2017-11-22 at 2 07 09 pm" src="https://user-images.githubusercontent.com/25493211/33145471-7d8c03d8-cf8e-11e7-83ec-7fec95688bde.png">
There is no switch next to the repository to enable it as the instructions specified.  What should i do next? 
@rivlev

**Comment by myang310** [comment]
Oh, push a commit and it should show up there. @MichaelGregg
